# Generated by Django 5.2 on 2025-09-28 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluationSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="评测集名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="评测集描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "评测集",
                "verbose_name_plural": "评测集",
                "db_table": "evaluation_sets",
            },
        ),
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="本次执行名称",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="总耗时(秒)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("running", "Running"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, null=True, verbose_name="配置参数"),
                ),
                (
                    "summary_metrics",
                    models.JSONField(
                        blank=True, null=True, verbose_name="整体指标汇总"
                    ),
                ),
                (
                    "evaluation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.evaluationset",
                        verbose_name="关联评测集",
                    ),
                ),
            ],
            options={
                "verbose_name": "评测执行记录",
                "verbose_name_plural": "评测执行记录",
                "db_table": "evaluation_runs",
            },
        ),
        migrations.CreateModel(
            name="Corpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="语料内容")),
                (
                    "corpus_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="语料类型"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, null=True, verbose_name="语料附加信息"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "evaluation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.evaluationset",
                        verbose_name="所属评测集",
                    ),
                ),
            ],
            options={
                "verbose_name": "语料",
                "verbose_name_plural": "语料",
                "db_table": "corpus",
            },
        ),
        migrations.CreateModel(
            name="CorpusResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_order",
                    models.IntegerField(blank=True, null=True, verbose_name="执行顺序"),
                ),
                ("result", models.JSONField(verbose_name="语料执行结果详情")),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, null=True, verbose_name="该语料的指标"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                        null=True,
                        verbose_name="单条语料执行状态",
                    ),
                ),
                (
                    "error_msg",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.corpus",
                        verbose_name="关联的语料",
                    ),
                ),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.evaluationrun",
                        verbose_name="关联的评测执行记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "语料执行结果",
                "verbose_name_plural": "语料执行结果",
                "db_table": "corpus_results",
                "indexes": [models.Index(fields=["corpus"], name="idx_corpus_results")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evaluation_run", "corpus"), name="uk_run_corpus"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="evaluationrun",
            index=models.Index(fields=["start_time"], name="idx_run_time"),
        ),
        migrations.AddIndex(
            model_name="corpus",
            index=models.Index(
                fields=["evaluation_set", "corpus_type"], name="idx_set_type"
            ),
        ),
    ]
