# Generated by Django 5.2 on 2025-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusresult",
            name="version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="版本"
            ),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="版本"
            ),
        ),
    ]
