# Generated by Django 5.2 on 2025-09-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_corpusresult_version_evaluationrun_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpusresult",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                max_length=50,
                null=True,
                verbose_name="版本",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationrun",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                max_length=50,
                null=True,
                verbose_name="版本",
            ),
        ),
    ]
