# Generated by Django 5.2 on 2025-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_corpusresult_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                max_length=50,
                null=True,
                verbose_name="版本",
            ),
        ),
    ]
