# Generated by Django 5.2 on 2025-09-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_corpus_version"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="corpus",
            name="idx_set_type",
        ),
        migrations.RemoveField(
            model_name="corpus",
            name="corpus_type",
        ),
        migrations.RemoveField(
            model_name="corpus",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="corpus",
            name="version",
        ),
        migrations.RemoveField(
            model_name="corpusresult",
            name="metrics",
        ),
        migrations.RemoveField(
            model_name="corpusresult",
            name="result",
        ),
        migrations.AddField(
            model_name="corpus",
            name="expected_response",
            field=models.TextField(blank=True, null=True, verbose_name="预期结果"),
        ),
        migrations.AddField(
            model_name="corpus",
            name="intent",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="意图"
            ),
        ),
        migrations.AddField(
            model_name="corpusresult",
            name="actual_response",
            field=models.TextField(default="", verbose_name="实际结果"),
        ),
        migrations.AddField(
            model_name="corpusresult",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="评分",
            ),
        ),
        migrations.AddIndex(
            model_name="corpus",
            index=models.Index(
                fields=["evaluation_set", "intent"], name="idx_set_intent"
            ),
        ),
    ]
